[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
PYTHON_VERSION = "3.11.0"
RAILWAY_STORAGE_PATH = "/data/storage" 